### ISSUE TITLE
Misleading title in dashboard module

### ISSUE THREAD

**Issue by pleimer** [infrawatch/documentation#101]
The title of the module explaining how to setup Grafana is misleading: https://github.com/infrawatch/documentation/blob/master/doc-Service-Telemetry-Framework/modules/proc_setting-up-the-dashboard-to-host-grafana.adoc

**Current:** `setting-up-the-dashboard-to-host-grafana`
**Proposed Change:** `setting-up-grafana-to-host-the-dashboard`

**Reason:** The dashboards do no host Grafana. Rather, Grafana hosts the dashboards

**Comment by JoanneOFlynn2018** [comment]
Thanks for logging this issue! Added to my to-do list!
