### ISSUE TITLE
Missing link in multi-cloud documentation

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/documentation#134]
This text does not render properly in the multi-cloud configuration. It may go away when doing the documentation for STF 1.1 but should be fixed regardless.

> To view example Smart Gateway manifests, see <<example-manifests_advanced-features[].

**Comment by JoanneOFlynn2018** [comment]
Thank you for submitting this issue Leif. I'll pick it up.

**Comment by leifmadsen** [comment]
@JoanneOFlynn2018 I've started on the re-write, so I think you can probably just ignore this.
