### ISSUE TITLE
Invalid procedure in "Creating an alert route in Alertmanager"

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/documentation#66]
In `doc-Service-Telemetry-Framework/modules/proc_creating-an-alert-route-in-alertmanager.adoc` at step 3, the deletion of `alertmanager-stf-default` is invalid because that `Secret` object is managed by the Service Telemetry Operator.

The proper procedure is to `oc edit servicetelemetry stf-default` and override the default `alertmanager-stf-default` secret with the `alertmanagerConfigManifest` parameter.

See https://github.com/infrawatch/service-telemetry-operator/blob/master/roles/servicetelemetry/tasks/component_alertmanager.yml#L1-L36 for how this is managed in the Operator.

**Comment by leifmadsen** [comment]
@mrunge this is a high priority and is a blocker for GA docs release.

**Comment by mrunge** [comment]
could you please be a bit more verbose? What does not work?

**Comment by leifmadsen** [comment]
> could you please be a bit more verbose? What does not work?

When you just delete this object, the STO is eventually going to reconcile and reset it back to the default. If you modify an object that is owned by the STO those object changes won't be persistent. You need to use the `_manifest` overrides as documented here: https://github.com/infrawatch/service-telemetry-operator/#overriding-default-manifests

Instead of modifying the Secret directly, you need to modify the `ServiceTelemetry` object and add the contents to the `alertmanagerConfigManifest`.
