### ISSUE TITLE
Dashboarding section needs validation procedure to check CSV

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/documentation#67]
The Dashboards section currently has a procedure to load the Grafana Operator via a Subscription without any validation or checks that the Operator was installed properly.

Follow the same validation methods in the Installation chapter so that someone knows how to run `oc get csv` and what to look for (grafana-operator is status `Succeeded`).

Do the same thing for `oc get pods` etc to validate the Grafana pod has started up successfully, etc.

**Comment by pleimer** [comment]
https://github.com/infrawatch/documentation/pull/76
