### ISSUE TITLE
Doc inconsistencies

### ISSUE THREAD

**Issue by JoanneOFlynn2018** [infrawatch/documentation#90]
Some links do not display correctly. 
Inconsistent use of the sub-heading "Procedure". 
Ensure that acronyms are defined at the start of each chapter.
Couple of missing shortdescs.
Most tables are missing numbers and captions.

Sweep entire document before release date.

**Comment by leifmadsen** [comment]
Just a heads up that I expect "release date" to be this week.

**Comment by leifmadsen** [comment]
@JoanneOFlynn2018 I merged your PR that I think covered this. Can we close this now?

**Comment by leifmadsen** [comment]
Closing as fixed. A lot of changes have happened since this was opened, and we've had several peer reviews.
